In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Users\krith\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np #Create 1D array from 0 to 9
array = np.arange(0,10)
print (array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
import numpy as np #Create a 3x3 array with all boolean values as true
array=np.ones(9)
new_array=array.reshape(3,3)
print(new_array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
import numpy as np #Extract all the odd numbers from an array of 1 to 10
a= np.array([1,2,3,4,5,6,7,8,9,10])
print("The List of Odd Numbers in this Array")
for i in range(len(a)):
    if (a[i] % 2==1):
        print(a[i])

The List of Odd Numbers in this Array
1
3
5
7
9


In [27]:
import numpy as np #Replace all the odd numbers as -1 in an array of 1 to 10
a= np.array([1,2,3,4,5,6,7,8,9,10])
print("The List of Odd Numbers in this Array")
a[a%2==1] =-1
print(a)

The List of Odd Numbers in this Array
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [35]:
import numpy as np #cONVERT 1d array to 2D array
array1=np.arange(0,4).reshape(2,2)
print(array1)

[[0 1]
 [2 3]]


In [37]:
import numpy as np #np.dot calculation
a=np.arange(20,29).reshape(3,3)
b=np.arange(40,49).reshape(3,3)
c=np.dot(a,b)
print(c)

[[2715 2778 2841]
 [3102 3174 3246]
 [3489 3570 3651]]


In [40]:
import numpy as np #np.sum calculation
a=np.arange(20,29).reshape(3,3)
b=np.arange(40,49).reshape(3,3)
c=np.dot(a,b)
sum=np.sum(c)
print(sum)

28566


In [41]:
import numpy as np #sum of all the columns
a=np.arange(20,29).reshape(3,3)
b=np.arange(40,49).reshape(3,3)
c=np.dot(a,b)
e=np.sum(c,axis=0)
print(e)

[9306 9522 9738]


In [42]:
import numpy as np #sum of all the rows
a=np.arange(20,29).reshape(3,3)
b=np.arange(40,49).reshape(3,3)
c=np.dot(a,b)
e=np.sum(c,axis=1)
print(e)

[ 8334  9522 10710]


In [45]:
n=1 #Create the pattern without hardcoding
a=np.array([n,n,n,n+1,n+1,n+1,n+2,n+2,n+2,n,n+1,n+2,n,n+1,n+2,n,n+1,n+2])
np.tile(a,1)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [56]:
a=np.array([1,2,3]) #Create the pattern using the funcitons repeat and tile
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [57]:
a=np.array([1,2,3,4,5]) #Remove repeating items present in array b ,which is 5 in this case
b=np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [93]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8,9])
ans= np.where(a>3) + np.where(b<7)
print(ans)

TypeError: '>' not supported between instances of 'list' and 'int'